data <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
names(data) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
data$datetime <- strptime(paste(data$Date,data$Time), format = "%d/%m/%Y %H:%M:%S")
data$Global_active_power <- as.numeric(data$Global_active_power)
with(data, plot(datetime, Global_active_power, type="l", xlab="", ylab = "Global Active Power (kilowatts)"))
dev.copy(png, file= "plot2.png", width = 480, height = 480)
dev.off()